### ISSUE TITLE
`-c` flag doesn't work

### ISSUE THREAD

**Issue by SteadyGiant** [frasermarlow/tap-bls#7]
Using Python 3.7 or 3.9 on Windows 10.

Install the tap and target:

```sh
python -m venv bls
bls/Scripts/pip install tap-bls  # bls/bin/pip on a Unix-like
```

Try running the tap in discover mode:

```sh
bls/Scripts/tap-bls -c sample_config.json --discover > catalog.json
```

But that throws this error:

```
CRITICAL '--config' is not in list
Traceback (most recent call last):
  File "path\to\bls\Scripts\tap-bls-script.py", line 11, in <module>
    load_entry_point('tap-bls==0.1.10', 'console_scripts', 'tap-bls')()
  File "path\to\bls\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "path\to\bls\lib\site-packages\tap_bls\__init__.py", line 42, in main
    generate_state()        # ... generate one
  File "path\to\bls\lib\site-packages\tap_bls\update_state.py", line 15, in generate_state
    state_file = sys.argv[sys.argv.index('--config')+1].rsplit('/', 1)[0]+"/state.json"
ValueError: '--config' is not in list
```

**It works if I use the `--config` arg.**

**Comment by frasermarlow** [comment]
Addressed in PR #11
